### PR TITLE
Release v1.2.0

### PR DESCRIPTION
**Pull request by amanjeev**

### CODE REVIEW

**Review by Hoverbear — COMMENTED** [review]
I asked you in DMs if you could look at if the install location changed due to `cargo-dist` updates.

**Comment by amanjeev** [comment]
Checked. Installs in the directories that are in the documentation  https://criticalup.ferrocene.dev/install.html

**Comment by Hoverbear** [comment]
Did manual validation on MacOS. @amanjeev did manual validation on Windows/Linux.

**Review by Hoverbear — APPROVED** [review]
Great!

**Pull request merged**
