### PR TITLE
Release v1.1.0

### PR DESCRIPTION
**Pull request by amanjeev**
Please see CHANGELOG.md for goodies in this release.

### CODE REVIEW

**Comment by pietroalbini** [comment]
We need to mark as bug fixed the removal of the timeout

**Review by Hoverbear — APPROVED** [review]
bors merge

**Comment by amanjeev** [comment]
bors cancel

**Comment by amanjeev** [comment]
> We need to mark as bug fixed the removal of the timeout

OK to just update CHANGELOG @pietroalbini ?

**Comment by pietroalbini** [comment]
Yep!

**Comment by Hoverbear** [comment]
We did not explicitly fix the timeout bug, it was fixed as a consequence of adding tokio. Let me make a PR adding it and you can rebase this.

**Review by Hoverbear — APPROVED** [review]
bors merge

**Pull request merged**
